export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_TOP_RATED_SHOWS = "GET_TOP_RATED_SHOWS";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_SHOW_DETAIL = "GET_SHOW_DETAIL";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SEARCH_SHOW = "SEARCH_SHOW";
export const GET_MOVIE_TRAILER = "GET_MOVIE_TRAILER";
export const GET_SHOW_TRAILER = "GET_SHOW_TRAILER";
